version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  sql-server-db:
    container_name: sql-server-db
    # image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-16.04
    build:
      context: ./sql-server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "nzwnVWDDC0Oj"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
