# Generated by Django 2.1.15 on 2020-03-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('questionid', models.IntegerField(db_column='QuestionID', primary_key=True, serialize=False)),
                ('questionnumber', models.CharField(blank=True, db_column='QuestionNumber', max_length=10, null=True)),
                ('questiontext', models.CharField(blank=True, db_column='QuestionText', max_length=5000, null=True)),
                ('leadinginstructions', models.CharField(blank=True, db_column='LeadingInstructions', max_length=255, null=True)),
                ('sequence', models.IntegerField(blank=True, db_column='Sequence', null=True)),
                ('acceptattachments', models.BooleanField(blank=True, db_column='AcceptAttachments', null=True)),
                ('startyear', models.IntegerField(db_column='StartYear')),
                ('endyear', models.IntegerField(blank=True, db_column='EndYear', null=True)),
            ],
            options={
                'db_table': 'Questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('sectionid', models.IntegerField(db_column='SectionID', primary_key=True, serialize=False)),
                ('sectiontitle', models.CharField(db_column='SectionTitle', max_length=150)),
                ('issubsection', models.BooleanField(db_column='IsSubsection')),
                ('parentsectionid', models.IntegerField(blank=True, db_column='ParentSectionID', null=True)),
                ('sequence', models.IntegerField(blank=True, db_column='Sequence', null=True)),
                ('startyear', models.IntegerField(db_column='StartYear')),
                ('endyear', models.IntegerField(blank=True, db_column='EndYear', null=True)),
            ],
            options={
                'db_table': 'Sections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('street_line_1', models.CharField(max_length=255)),
                ('street_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('zipcode', models.CharField(max_length=10)),
            ],
        ),
    ]
