# Generated by Django 2.1.15 on 2020-03-27 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
