# Generated by Django 2.2.12 on 2020-05-05 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('questionid', models.IntegerField(
                    db_column='QuestionID', primary_key=True, serialize=False)),
                ('questionnumber', models.CharField(blank=True,
                                                    db_column='QuestionNumber', max_length=10, null=True)),
                ('questiontext', models.CharField(blank=True,
                                                  db_column='QuestionText', max_length=4000, null=True)),
                ('leadinginstructions', models.CharField(blank=True,
                                                         db_column='LeadingInstructions', max_length=255, null=True)),
                ('sequence', models.IntegerField(
                    blank=True, db_column='Sequence', null=True)),
                ('acceptattachments', models.BooleanField(
                    blank=True, db_column='AcceptAttachments', null=True)),
                ('startyear', models.IntegerField(db_column='StartYear')),
                ('endyear', models.IntegerField(
                    blank=True, db_column='EndYear', null=True)),
                ('sectionid', models.OneToOneField(blank=True, db_column='SectionID', null=True,
                                                   on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.Sections')),
            ],
            options={
                'managed': False,
                'db_table': 'Questions',
            },
        ),
    ]
