# Generated by Django 2.1.15 on 2020-03-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_delete_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='Year')),
                ('answertext', models.CharField(blank=True, db_column='AnswerText', max_length=7500, null=True)),
                ('answerchoices', models.CharField(blank=True, db_column='AnswerChoices', max_length=150, null=True)),
            ],
            options={
                'db_table': 'Answers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questionelement',
            fields=[
                ('elementid', models.IntegerField(db_column='ElementID', primary_key=True, serialize=False)),
                ('maxlength', models.IntegerField(blank=True, db_column='MaxLength', null=True)),
                ('sequence', models.IntegerField(blank=True, db_column='Sequence', null=True)),
                ('startyear', models.IntegerField(db_column='StartYear')),
                ('endyear', models.IntegerField(blank=True, db_column='EndYear', null=True)),
                ('type1description', models.CharField(blank=True, db_column='Type1Description', max_length=225, null=True)),
                ('type2description', models.CharField(blank=True, db_column='Type2Description', max_length=100, null=True)),
                ('linktoelementid', models.IntegerField(blank=True, db_column='LinkToElementID', null=True)),
                ('linktoelementvalue', models.CharField(blank=True, db_column='LinkToElementValue', max_length=150, null=True)),
                ('linktoquestiontypeid', models.IntegerField(blank=True, db_column='LinkToQuestionTypeID', null=True)),
                ('requiredforcert', models.BooleanField(blank=True, db_column='RequiredForCert', null=True)),
            ],
            options={
                'db_table': 'QuestionElement',
                'managed': False,
            },
        ),
    ]
